#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle (simplified, Apache-2.0).
# Delegates to gradle/wrapper/gradle-wrapper.jar (GradleWrapperMain).
#

# Resolve the application home directory (follow symlinks).
app_path=$0
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld -- "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "$CLASSPATH" ]; then
    echo "ERROR: $CLASSPATH is missing." >&2
    echo "The Gradle wrapper jar is not committed to this repository." >&2
    echo "Recover it once (either of these works):" >&2
    echo "  1) Open the project in Android Studio (it provisions the wrapper automatically), or" >&2
    echo "  2) With Gradle 8.x on PATH run:  gradle wrapper --gradle-version 8.6" >&2
    exit 1
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        echo "Please set the JAVA_HOME variable to match your Java installation." >&2
        exit 1
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1 ; then
        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
        echo "Install JDK 17 and/or set JAVA_HOME." >&2
        exit 1
    fi
fi

# Collect all arguments for the java command.
# * $DEFAULT_JVM_OPTS, $JAVA_OPTS and $GRADLE_OPTS can contain fragments of
#   shell script including quotes and/or backslashes, so put them in
#   temporary variables so that they are expanded atomically.
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "\"\$@\""

exec "$JAVACMD" "$@"
